import { EmailTemplateProps } from "@/lib/interfaces";

export function EmailTemplate({ stageId, tracking }: EmailTemplateProps) {
  const getEmailContent = () => {
    switch (stageId) {
      case "stage-1":
        return {
          heading: "Shipping Label Ready – Send Your Parcel",
          message: `Your FedEx shipping label has been generated with tracking ${tracking} to send the product to Crystal Fusion (Netherlands).
Please print the label, attach it to the parcel, and proceed with shipping. Shipment details have been recorded on the blockchain.`,
        };
      case "stage-2":
        return {
          heading: "Parcel Dispatched to Production Unit 1",
          message: `Your product has been picked up from Crystal Fusion and is now en route to Production Unit 1.
Tracking details have been shared with the production team. Shipment has been securely recorded on the blockchain.
Tracking: ${tracking}`,
        };
      case "stage-4":
        return {
          heading: "Your Parcel is on Its Way!",
          message: `Your product has been shipped with tracking ${tracking} from Belgium and is on its way to you.
The shipping label was generated by Crystal Fusion. Blockchain record confirms the shipment details.`,
        };
      default:
        return {
          heading: "Update from Crystal Fusion",
          message: `We're keeping you updated with your order. Further details will be shared shortly.`,
        };
    }
  };

  const { heading, message } = getEmailContent();

  return (
    <div style={{ fontFamily: "Arial, sans-serif", padding: "20px" }}>
      <h1 style={{ color: "#1E3A8A" }}>{heading}</h1>
      <p style={{ fontSize: "14px", color: "#333" }}>{message}</p>
      <p style={{ fontSize: "12px", color: "#555", marginTop: "20px" }}>
        — Crystal Fusion Team
      </p>
    </div>
  );
}
